<html>
 <head><link rel="stylesheet" type="text/css" href="style2.css"></head>
 <body>
  <nav id="menu">
   <h1>Menu Principal</h1>
    <ul>
     <li><a href='ciadodoce.php'>Inicio</a></li>
     <li><a href='#'>  </a></li>
     <li><a href='#dicas'> Dicas </a></li>
     <li><a href='#'>  </a></li>
     <li><a href='#contato'> Contato </a></li>
     <li><a href='#'></a></li>       
     <li><a href='#sobre'> Sobre </a></li>
   </ul>
  </nav>
 </body>
</html>
